name: Windows Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: compile & test
      run: |
        dir
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
        cmake --build build --target SDL2
        cmake --build build --target test
        ./build/test/Debug/test.exe
        cmake --build build --target main
